# Generated by Django 4.0.3 on 2022-03-20 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pickle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1.0)),
                ('user', models.BigIntegerField()),
                ('pickle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickles.pickle')),
            ],
        ),
        migrations.CreateModel(
            name='PickleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickles.pickle')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickles.tag')),
            ],
        ),
    ]
