# Generated by Django 4.0.3 on 2022-03-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickles', '0002_rating_created_date_alter_pickle_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickle',
            name='maker',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
