# Generated by Django 4.0.3 on 2022-03-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickles', '0006_add_pickle_maker_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickle',
            name='maker',
            field=models.CharField(db_column='maker_old', max_length=256),
        ),
    ]
