# Generated by Django 4.0.3 on 2022-03-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickles', '0007_alter_pickle_maker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickle',
            old_name='maker',
            new_name='maker_old',
        ),
    ]
