# Generated by Django 4.0.3 on 2022-03-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickles', '0008_rename_maker_pickle_maker_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickle',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pickles.picklemaker'),
        ),
    ]
