# Generated by Django 4.0.3 on 2022-03-22 10:32

from django.db import migrations

def add_picklemaker_foreign_keys(apps, schema_editor):
    """Add picklemaker foreign keys to the pickle table"""
    PickleMaker = apps.get_model('pickles', 'PickleMaker')
    maker_name_to_picklemaker = {x.name:x for x in PickleMaker.objects.all()}
    for pickle in Pickle.objects.all():
        picklemaker = maker_name_to_picklemaker[pickle.maker_old]
        pickle.maker = picklemaker
        pickle.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pickles', '0009_pickle_maker'),
    ]

    operations = [
        migrations.RunPython(add_picklemaker_foreign_keys)
    ]
