# Generated by Django 4.0.3 on 2022-03-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickles', '0010_populate_picklemaker_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickle',
            name='maker_old',
        ),
        migrations.AlterField(
            model_name='pickle',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickles.picklemaker'),
        ),
    ]
